// Drop-in form of an exported project: every source and header in one flat folder
// with project #includes rewritten to match, the project's assets compiled into
// studio_assets.cpp (so fonts load whatever the host's working directory is), and a
// CMakeLists.txt that builds the UI as a static library against the host's Dear ImGui.
import fs from 'node:fs';
import path from 'node:path';
import { toPosix } from './util.js';

const HEADER_EXT = /\.(h|hh|hpp|hxx|inl)$/i;
// main.cpp is renamed too: in a host project it would read as the file holding main().
const RESERVED = new Set(['main.cpp', 'studio.h', 'studio_app.h', 'studio_assets.h', 'studio_assets.cpp', 'CMakeLists.txt', 'README.md']);
// Embedding is for fonts, icons and small images; past this the assets stay files on disk.
const MAX_EMBED_BYTES = 16 * 1024 * 1024;

// Unique flat names: basename, or the project path with '/' -> '_' when two files share one.
function flatNames(files) {
  const count = new Map();
  for (const f of files) count.set(path.posix.basename(f), (count.get(path.posix.basename(f)) || 0) + 1);
  const map = new Map();
  for (const f of files) {
    const base = path.posix.basename(f);
    map.set(f, count.get(base) > 1 || RESERVED.has(base) ? f.replace(/\//g, '_') : base);
  }
  return map;
}

// Rewrite #include "x" / <x> that resolve (like the compiler would: next to the file,
// then the include dirs) to a project file, to that file's flat name.
function rewriteIncludes(text, rel, flat, includeDirs) {
  return text.replace(/^([ \t]*#[ \t]*include[ \t]*)(["<])([^">\n]+)[">]/gm, (m, lead, open, name) => {
    const dirs = [...(open === '"' ? [path.posix.dirname(rel)] : []), ...includeDirs];
    for (const d of dirs) {
      const cand = path.posix.normalize(path.posix.join(d, name)).replace(/^\.\//, '');
      if (flat.has(cand)) return `${lead}"${flat.get(cand)}"`;
    }
    return m;
  });
}

// Start of the postfix expression ending just before `end` (e.g. `ImGui::GetIO().Fonts`).
function receiverStart(text, end) {
  let i = end;
  while (i > 0 && /\s/.test(text[i - 1])) i--;
  for (;;) {
    // Call / subscript groups: `f(...)`, `a[...]`; a bare `(...)` ends the expression.
    while (text[i - 1] === ')' || text[i - 1] === ']') {
      const close = text[i - 1];
      const open = close === ')' ? '(' : '[';
      let depth = 0;
      while (i > 0) {
        const c = text[--i];
        if (c === close) depth++;
        else if (c === open && --depth === 0) break;
      }
    }
    let j = i;
    while (j > 0 && /[\w]/.test(text[j - 1])) j--;
    if (j === i) return i;
    i = j;
    let k = i;
    while (k > 0 && /\s/.test(text[k - 1])) k--;
    if (text.slice(k - 2, k) === '::' || text.slice(k - 2, k) === '->') i = k - 2;
    else if (text[k - 1] === '.') i = k - 1;
    else return i;
    while (i > 0 && /\s/.test(text[i - 1])) i--;
  }
}

// Route file access in the sources through StudioAssets so embedded assets are found.
export function rewriteAssetAccess(text) {
  let changed = false;
  // atlas->AddFontFromFileTTF(...) / atlas.AddFontFromFileTTF(...)
  const re = /(->|\.)\s*AddFontFromFileTTF\s*\(/g;
  let out = '';
  let last = 0;
  for (let m; (m = re.exec(text)); ) {
    const start = receiverStart(text, m.index);
    const recv = text.slice(start, m.index).trim();
    if (!recv) continue;
    out += text.slice(last, start) + `StudioAssets::AddFontFromFileTTF(${m[1] === '->' ? recv : `&(${recv})`}, `;
    last = m.index + m[0].length;
    changed = true;
  }
  text = out + text.slice(last);
  const before = text;
  text = text
    .replace(/(^|[^\w.>:])(?:std)?::\s*fopen\s*\(|(^|[^\w.>:])fopen\s*\(/gm, (m, a, b) => `${a ?? b ?? ''}StudioAssets::Open(`)
    .replace(/(^|[^\w.>:])ImFileLoadToMemory\s*\(/gm, '$1StudioAssets::LoadToMemory(');
  changed ||= text !== before;
  if (!changed) return null;
  // Include the asset header right after the first #include (after #pragma once in headers).
  const inc = /^[ \t]*#[ \t]*include[^\n]*\n/m.exec(text);
  const at = inc ? inc.index + inc[0].length : 0;
  return `${text.slice(0, at)}#include "studio_assets.h"\n${text.slice(at)}`;
}

function bytesToC(buf) {
  const lines = [];
  for (let i = 0; i < buf.length; i += 32) lines.push(`    ${Array.from(buf.subarray(i, i + 32)).join(',')},`);
  return lines.join('\n');
}

const ASSETS_H = `// studio_assets.h - generated by ImGui Studio.
// The project's assets are compiled in, so the UI loads its fonts and files from
// memory instead of paths relative to the working directory. Lookups use the same
// relative paths as the project (e.g. "assets/fonts/Inter-Regular.ttf"); anything
// not embedded falls through to the file system.
#pragma once

#include "imgui.h"
#include <cstddef>
#include <cstdio>

namespace StudioAssets
{
    // Embedded bytes for a project-relative path, or nullptr.
    const unsigned char* Find(const char* path, size_t* out_size = nullptr);

    // fopen() replacement: read modes on an embedded path return a temporary FILE*
    // holding the asset; everything else is a plain fopen().
    FILE* Open(const char* path, const char* mode);

    // ImFontAtlas::AddFontFromFileTTF() that prefers the embedded copy.
    ImFont* AddFontFromFileTTF(ImFontAtlas* atlas, const char* filename, float size_pixels = 0.0f,
                               const ImFontConfig* font_cfg = nullptr, const ImWchar* glyph_ranges = nullptr);

    // ImFileLoadToMemory() that prefers the embedded copy (free the result with IM_FREE).
    void* LoadToMemory(const char* filename, const char* mode, size_t* out_file_size = nullptr, int padding_bytes = 0);
}
`;

function assetsCpp(assets) {
  const arrays = assets.map((a, i) => `alignas(4) const unsigned char kAsset${i}[] = {\n${bytesToC(a.data)}\n};`).join('\n\n');
  const table = assets.map((a, i) => `    { ${JSON.stringify(a.rel)}, kAsset${i}, sizeof(kAsset${i}) },`).join('\n');
  return `// studio_assets.cpp - generated by ImGui Studio: ${assets.length} embedded asset(s).
#if defined(_MSC_VER) && !defined(_CRT_SECURE_NO_WARNINGS)
#define _CRT_SECURE_NO_WARNINGS
#endif
#include "studio_assets.h"
#include "imgui_internal.h"
#include <cstring>

namespace
{
    struct Asset { const char* path; const unsigned char* data; size_t size; };

${arrays.replace(/^/gm, '    ').replace(/^ {4}$/gm, '')}

    const Asset kAssets[] = {
${table.replace(/^/gm, '    ')}
    };

    // "./assets\\\\fonts/x.ttf" == "assets/fonts/x.ttf"
    bool SamePath(const char* a, const char* b)
    {
        while (a[0] == '.' && (a[1] == '/' || a[1] == '\\\\')) a += 2;
        while (b[0] == '.' && (b[1] == '/' || b[1] == '\\\\')) b += 2;
        for (; *a && *b; a++, b++)
        {
            char ca = *a == '\\\\' ? '/' : *a, cb = *b == '\\\\' ? '/' : *b;
            if (ca != cb) return false;
        }
        return *a == *b;
    }
}

namespace StudioAssets
{
    const unsigned char* Find(const char* path, size_t* out_size)
    {
        if (path)
            for (const Asset& a : kAssets)
                if (SamePath(path, a.path))
                {
                    if (out_size) *out_size = a.size;
                    return a.data;
                }
        return nullptr;
    }

    FILE* Open(const char* path, const char* mode)
    {
        size_t size = 0;
        const unsigned char* data = Find(path, &size);
        if (data && mode && mode[0] == 'r' && !strchr(mode, '+'))
            if (FILE* f = tmpfile())
            {
                if (fwrite(data, 1, size, f) == size && fseek(f, 0, SEEK_SET) == 0)
                    return f;
                fclose(f);
            }
        return fopen(path, mode);
    }

    ImFont* AddFontFromFileTTF(ImFontAtlas* atlas, const char* filename, float size_pixels, const ImFontConfig* font_cfg, const ImWchar* glyph_ranges)
    {
        size_t size = 0;
        const unsigned char* data = Find(filename, &size);
        if (!data)
            return atlas->AddFontFromFileTTF(filename, size_pixels, font_cfg, glyph_ranges);
        void* copy = IM_ALLOC(size);  // the atlas owns and frees it
        memcpy(copy, data, size);
        ImFontConfig cfg = font_cfg ? *font_cfg : ImFontConfig();
        cfg.FontDataOwnedByAtlas = true;
        if (cfg.Name[0] == '\\0')
        {
            const char* base = filename;
            for (const char* p = filename; *p; p++)
                if (*p == '/' || *p == '\\\\') base = p + 1;
            ImStrncpy(cfg.Name, base, IM_ARRAYSIZE(cfg.Name));
        }
        return atlas->AddFontFromMemoryTTF(copy, (int)size, size_pixels, &cfg, glyph_ranges);
    }

    void* LoadToMemory(const char* filename, const char* mode, size_t* out_file_size, int padding_bytes)
    {
        size_t size = 0;
        const unsigned char* data = Find(filename, &size);
        if (!data)
            return ImFileLoadToMemory(filename, mode, out_file_size, padding_bytes);
        unsigned char* copy = (unsigned char*)IM_ALLOC(size + (size_t)padding_bytes);
        memcpy(copy, data, size);
        memset(copy + size, 0, (size_t)padding_bytes);
        if (out_file_size) *out_file_size = size;
        return copy;
    }
}
`;
}

function embedCmake({ target, sources, defines, cxxStd }) {
  const std = (String(cxxStd).match(/(\d+)/) || [null, '17'])[1];
  return `# Generated by ImGui Studio: the UI as a drop-in static library.
#
#   add_subdirectory(path/to/embed)
#   target_link_libraries(your_app PRIVATE ${target})
#
# Links your Dear ImGui CMake target (default name "imgui", override with
# ${target.toUpperCase()}_IMGUI_TARGET), or, without one, adds IMGUI_DIR to the include path.
cmake_minimum_required(VERSION 3.16)
project(${target} LANGUAGES CXX)

add_library(${target} STATIC
${sources.map((s) => `    \${CMAKE_CURRENT_SOURCE_DIR}/${s}`).join('\n')}
)
target_compile_features(${target} PUBLIC cxx_std_${std})
target_include_directories(${target} PUBLIC \${CMAKE_CURRENT_SOURCE_DIR})
${defines.length ? `target_compile_definitions(${target} PRIVATE ${defines.join(' ')})\n` : ''}
set(${target.toUpperCase()}_IMGUI_TARGET imgui CACHE STRING "CMake target that provides Dear ImGui")
if(TARGET \${${target.toUpperCase()}_IMGUI_TARGET})
  target_link_libraries(${target} PUBLIC \${${target.toUpperCase()}_IMGUI_TARGET})
elseif(DEFINED IMGUI_DIR)
  target_include_directories(${target} PUBLIC \${IMGUI_DIR})
else()
  message(FATAL_ERROR "${target}: no Dear ImGui target named '\${${target.toUpperCase()}_IMGUI_TARGET}'. Set ${target.toUpperCase()}_IMGUI_TARGET or IMGUI_DIR.")
endif()
`;
}

function embedReadme({ title, target, files, embedded, imguiVersion }) {
  return `# ${title} - drop-in sources

Copy this folder into your application. It contains only your UI code plus
small helpers; it uses **your** Dear ImGui (built against v${imguiVersion}; any 1.92+
should work).

## Add it to your build

- **CMake**: \`add_subdirectory(embed)\` then \`target_link_libraries(your_app PRIVATE ${target})\`
  (it links your \`imgui\` target, see CMakeLists.txt).
- **Visual Studio / Makefile / anything else**: add every \`.cpp\` here to your project
  and make sure the directory with \`imgui.h\` is on the include path. No other
  include paths or defines are needed: includes between these files are local.

\`\`\`
${files.join('\n')}
\`\`\`

## Call it

\`\`\`cpp
#include "studio_app.h"

// once, after ImGui::CreateContext() and your platform/renderer backends:
AppInit();

// every frame, between ImGui::NewFrame() and ImGui::Render():
AppFrame();
\`\`\`

${embedded.length ? `## Assets

${embedded.length} asset file(s) are compiled into \`studio_assets.cpp\`, so the UI finds
its fonts no matter what the working directory is. File access in the sources was
routed through \`StudioAssets\` (\`studio_assets.h\`) to make that work.
` : ''}
\`studio.h\` holds ImGui Studio's instrumentation macros; they compile to nothing
unless \`IMGUI_STUDIO\` is defined.
`;
}

// Writes the embed/ folder through add(rel, data); returns a summary.
export async function writeEmbed({ projectDir, cfg, sources, assetDirs, projectImgui, target, imguiVersion, studioHeaders, walk, add }) {
  const inImgui = (f) => projectImgui && (f === projectImgui || f.startsWith(`${projectImgui}/`));
  const headers = walk.filter((f) => HEADER_EXT.test(f) && !inImgui(f) && !f.startsWith('native/'));
  const files = [...sources, ...headers];
  const flat = flatNames(files);
  const includeDirs = cfg.include_dirs.map((d) => path.posix.normalize(toPosix(d)));

  const embedded = [];
  let total = 0;
  for (const dir of assetDirs) {
    for (const rel of walk.filter((f) => f.startsWith(`${dir}/`))) {
      const data = fs.readFileSync(path.join(projectDir, rel));
      embedded.push({ rel, data });
      total += data.length;
    }
  }
  const embedAssets = embedded.length > 0 && total <= MAX_EMBED_BYTES;

  const out = [];
  const rewritten = [];
  for (const rel of files) {
    let text = rewriteIncludes(fs.readFileSync(path.join(projectDir, rel), 'utf8'), rel, flat, includeDirs);
    if (embedAssets) {
      const r = rewriteAssetAccess(text);
      if (r) {
        text = r;
        rewritten.push(flat.get(rel));
      }
    }
    await add(`embed/${flat.get(rel)}`, text);
    out.push(flat.get(rel));
  }
  for (const [name, data] of Object.entries(studioHeaders)) {
    await add(`embed/${name}`, data);
    out.push(name);
  }
  const cppFiles = sources.map((s) => flat.get(s));
  if (embedAssets) {
    await add('embed/studio_assets.h', ASSETS_H);
    await add('embed/studio_assets.cpp', assetsCpp(embedded));
    out.push('studio_assets.h', 'studio_assets.cpp');
    cppFiles.push('studio_assets.cpp');
    // Licences travel with the embedded fonts.
    for (const a of embedded.filter((e) => /licen[cs]e|copying|notice/i.test(e.rel))) await add(`embed/licenses/${path.posix.basename(a.rel)}`, a.data);
  }
  await add('embed/CMakeLists.txt', embedCmake({ target, sources: cppFiles, defines: cfg.defines, cxxStd: cfg.cxx_std }));
  await add('embed/README.md', embedReadme({ title: cfg.name, target, files: out.sort(), embedded: embedAssets ? embedded : [], imguiVersion }));
  return {
    dir: 'embed',
    target,
    files: out.sort(),
    assets_embedded: embedAssets ? embedded.map((e) => e.rel) : [],
    asset_access_rewritten: rewritten,
    note: embedded.length && !embedAssets ? `Assets total ${total} bytes (> ${MAX_EMBED_BYTES}); not embedded - ship ${assetDirs.join(', ')} next to the executable.` : undefined,
  };
}
