// Export a Studio project as a plain native Dear ImGui project (GLFW + OpenGL3 host,
// CMake build), and check that the sources compile natively without IMGUI_STUDIO.
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { spawn, execFileSync } from 'node:child_process';
import { BUILTIN_IMGUI_DIR, RUNTIME_DIR, STUDIO_ROOT, imguiDirFor, loadProjectConfig } from './config.js';
import { makePathMapper, parseDiagnostics } from './diagnostics.js';
import { createZip } from './zip.js';
import { writeEmbed } from './embed.js';
import { ensureDir, globToRegExp, mapLimit, parseColor, toPosix, walkFiles } from './util.js';
import os from 'node:os';

const SOURCE_EXT = /\.(cpp|cc|cxx|c)$/i;

function slug(s) {
  return String(s || 'imgui-app')
    .replace(/[^a-z0-9]+/gi, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase() || 'imgui-app';
}

function cmakeTarget(s) {
  return slug(s).replace(/-/g, '_');
}

function projectSources(projectDir, cfg) {
  const include = cfg.sources.map(globToRegExp);
  const exclude = cfg.exclude.map(globToRegExp);
  return walkFiles(projectDir)
    .filter((f) => SOURCE_EXT.test(f))
    .filter((f) => include.some((re) => re.test(f)))
    .filter((f) => !exclude.some((re) => re.test(f)));
}

const IMGUI_FILES = [
  'imgui.cpp', 'imgui.h', 'imgui_internal.h', 'imgui_draw.cpp', 'imgui_widgets.cpp', 'imgui_tables.cpp', 'imgui_demo.cpp',
  'imconfig.h', 'imstb_rectpack.h', 'imstb_textedit.h', 'imstb_truetype.h', 'LICENSE.txt',
  'backends/imgui_impl_glfw.cpp', 'backends/imgui_impl_glfw.h', 'backends/imgui_impl_opengl3.cpp', 'backends/imgui_impl_opengl3.h',
  'backends/imgui_impl_opengl3_loader.h', 'misc/cpp/imgui_stdlib.cpp', 'misc/cpp/imgui_stdlib.h',
];

function cmakeLists({ target, uiTarget, title, assetDirs }) {
  const copies = assetDirs
    .map(
      (d) => `add_custom_command(TARGET ${target} POST_BUILD
    COMMAND \${CMAKE_COMMAND} -E copy_directory \${CMAKE_CURRENT_SOURCE_DIR}/${d} $<TARGET_FILE_DIR:${target}>/${d})`,
    )
    .join('\n');
  return `# Generated by ImGui Studio: native build of "${title}".
#   cmake -S . -B build && cmake --build build
# Uses a system GLFW 3 if available, otherwise downloads it (FetchContent).
# The UI itself is built from embed/, the drop-in copy of your sources.
cmake_minimum_required(VERSION 3.16)
project(${target} LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(OpenGL REQUIRED)
find_package(glfw3 3.3 QUIET)
if(NOT glfw3_FOUND)
  include(FetchContent)
  set(GLFW_BUILD_DOCS OFF CACHE BOOL "" FORCE)
  set(GLFW_BUILD_TESTS OFF CACHE BOOL "" FORCE)
  set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
  FetchContent_Declare(glfw GIT_REPOSITORY https://github.com/glfw/glfw.git GIT_TAG 3.4)
  FetchContent_MakeAvailable(glfw)
endif()

set(IMGUI_DIR \${CMAKE_CURRENT_SOURCE_DIR}/imgui)
add_library(imgui STATIC
    \${IMGUI_DIR}/imgui.cpp
    \${IMGUI_DIR}/imgui_draw.cpp
    \${IMGUI_DIR}/imgui_widgets.cpp
    \${IMGUI_DIR}/imgui_tables.cpp
    \${IMGUI_DIR}/imgui_demo.cpp
    \${IMGUI_DIR}/misc/cpp/imgui_stdlib.cpp
    \${IMGUI_DIR}/backends/imgui_impl_glfw.cpp
    \${IMGUI_DIR}/backends/imgui_impl_opengl3.cpp
)
target_include_directories(imgui PUBLIC \${IMGUI_DIR} \${IMGUI_DIR}/backends)
target_link_libraries(imgui PUBLIC glfw OpenGL::GL)

add_subdirectory(embed)

add_executable(${target} native/main.cpp)
target_link_libraries(${target} PRIVATE ${uiTarget} imgui)
${assetDirs.length ? `
# Your code loads assets relative to the working directory: copy them next to the executable.
${copies}
set_property(TARGET ${target} PROPERTY VS_DEBUGGER_WORKING_DIRECTORY $<TARGET_FILE_DIR:${target}>)
` : ''}`;
}

function readme({ title, target, uiTarget, embed }) {
  return `# ${title} (exported from ImGui Studio)

This is plain C++ Dear ImGui code. Nothing here depends on ImGui Studio: the
instrumentation macros in \`studio.h\` compile to nothing unless
\`IMGUI_STUDIO\` is defined.

## Add the menu to your own project

Use the \`embed/\` folder: your UI sources in one flat folder (no extra include
paths needed)${embed.assets_embedded.length ? ', with fonts and other assets compiled in so nothing depends on the working directory' : ''}.

- CMake: \`add_subdirectory(embed)\` + \`target_link_libraries(your_app PRIVATE ${uiTarget})\`
- Any other build system: add every \`.cpp\` in \`embed/\` and keep \`imgui.h\` on the include path.

Then call \`AppInit()\` once after creating your Dear ImGui context and backends,
and \`AppFrame()\` every frame between \`ImGui::NewFrame()\` and \`ImGui::Render()\`.
See \`embed/README.md\`.

## Build and run the standalone app

\`\`\`sh
cmake -S . -B build
cmake --build build --config Release
./build/${target}
\`\`\`

Requirements: a C++17 compiler, CMake 3.16+, OpenGL. GLFW is used from your
system when available, otherwise fetched automatically. \`native/main.cpp\` is
the GLFW + OpenGL 3 host; it shows exactly where \`AppInit()\`/\`AppFrame()\` go.

## Layout

- \`embed/\` - drop-in UI sources (what the build uses)
- \`imgui/\` - the Dear ImGui the Studio previewed with
- \`native/main.cpp\` - standalone host
- the other folders are your Studio project sources as written, for reference
`;
}

export async function exportProject(studio, { dest = null, zip = true, includeImgui = true } = {}) {
  const projectDir = studio.projectDir;
  const cfg = loadProjectConfig(projectDir);
  const buildId = studio.latestBuildId();
  const name = slug(cfg.name);
  const outDir = dest ? path.resolve(projectDir, dest) : path.join(projectDir, 'export', `${name}${buildId ? `-build${buildId}` : ''}`);
  await fsp.rm(outDir, { recursive: true, force: true });
  await ensureDir(outDir);
  const files = [];
  const add = async (rel, data) => {
    const abs = path.join(outDir, rel);
    await ensureDir(path.dirname(abs));
    await fsp.writeFile(abs, data);
    files.push(rel);
  };

  // Project files (sources, headers, assets); Studio state and exports are skipped by walkFiles.
  const projectImgui = cfg.imgui && cfg.imgui !== 'builtin' ? toPosix(path.relative(projectDir, imguiDirFor(projectDir, cfg))) : null;
  for (const rel of walkFiles(projectDir)) {
    if (rel === 'studio.json' || rel === 'CLAUDE.md' || rel === '.mcp.json') continue;
    if (projectImgui && (rel === projectImgui || rel.startsWith(`${projectImgui}/`))) continue;
    await add(rel, await fsp.readFile(path.join(projectDir, rel)));
  }
  await add('studio/studio.h', await fsp.readFile(path.join(RUNTIME_DIR, 'include', 'studio.h')));
  await add('studio/studio_app.h', await fsp.readFile(path.join(RUNTIME_DIR, 'include', 'studio_app.h')));

  if (includeImgui) {
    const srcImgui = projectImgui ? path.join(projectDir, projectImgui) : BUILTIN_IMGUI_DIR;
    for (const f of IMGUI_FILES) {
      const from = fs.existsSync(path.join(srcImgui, f)) ? path.join(srcImgui, f) : path.join(BUILTIN_IMGUI_DIR, f);
      if (fs.existsSync(from)) await add(`imgui/${f}`, await fsp.readFile(from));
    }
  }

  const clear = parseColor(cfg.background);
  const main = (await fsp.readFile(path.join(RUNTIME_DIR, 'native', 'main.cpp'), 'utf8'))
    .replace('{{TITLE}}', String(cfg.name).replace(/["\\]/g, ''))
    .replace('{{WIDTH}}', String(cfg.viewport.width))
    .replace('{{HEIGHT}}', String(cfg.viewport.height))
    .replace('{{CLEAR_R}}', clear[0].toFixed(4))
    .replace('{{CLEAR_G}}', clear[1].toFixed(4))
    .replace('{{CLEAR_B}}', clear[2].toFixed(4));
  await add('native/main.cpp', main);

  const sources = projectSources(projectDir, cfg);
  const assetDirs = cfg.assets.filter((d) => fs.existsSync(path.join(projectDir, d))).map((d) => toPosix(path.normalize(d)));
  const target = cmakeTarget(cfg.name);
  const uiTarget = `${target}_ui`;
  const imguiH = fs.readFileSync(path.join(projectImgui ? path.join(projectDir, projectImgui) : BUILTIN_IMGUI_DIR, 'imgui.h'), 'utf8');
  const embed = await writeEmbed({
    projectDir,
    cfg,
    sources,
    assetDirs,
    projectImgui,
    target: uiTarget,
    imguiVersion: (imguiH.match(/#define IMGUI_VERSION\s+"([^"]+)"/) || [null, '?'])[1],
    studioHeaders: {
      'studio.h': await fsp.readFile(path.join(RUNTIME_DIR, 'include', 'studio.h')),
      'studio_app.h': await fsp.readFile(path.join(RUNTIME_DIR, 'include', 'studio_app.h')),
    },
    walk: walkFiles(projectDir),
    add,
  });
  await add('CMakeLists.txt', cmakeLists({ target, uiTarget, title: cfg.name, assetDirs: embed.assets_embedded.length ? [] : assetDirs }));
  await add('README.md', readme({ title: cfg.name, target, uiTarget, embed }));

  let zipPath = null;
  if (zip) {
    const entries = [];
    for (const rel of files) entries.push({ name: `${path.basename(outDir)}/${rel}`, data: await fsp.readFile(path.join(outDir, rel)) });
    zipPath = `${outDir}.zip`;
    await fsp.writeFile(zipPath, createZip(entries));
  }
  return {
    export_dir: outDir,
    zip: zipPath,
    zip_url: zipPath ? `/project-files/${toPosix(path.relative(projectDir, zipPath))}` : null,
    build_id: buildId,
    files: files.length,
    sources,
    embed,
    entry_points: 'AppInit() / AppFrame() (see embed/studio_app.h)',
    integrate: `Drop-in sources: ${path.join(outDir, 'embed')} (add_subdirectory(embed) + link ${uiTarget}, or add its .cpp files to any build)`,
    build_instructions: 'cmake -S . -B build && cmake --build build',
  };
}

function findHostCompiler() {
  for (const c of [process.env.CXX, 'clang++', 'g++', 'c++'].filter(Boolean)) {
    try {
      const v = execFileSync(c, ['--version'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).split('\n')[0];
      return { cxx: c, version: v };
    } catch {
      // try next
    }
  }
  return null;
}

function run(cmd, args, opts) {
  return new Promise((resolve) => {
    const child = spawn(cmd, args, { ...opts, stdio: ['ignore', 'pipe', 'pipe'] });
    let out = '';
    child.stdout.on('data', (d) => (out += d));
    child.stderr.on('data', (d) => (out += d));
    child.on('error', (e) => resolve({ code: -1, output: e.message }));
    child.on('close', (code) => resolve({ code, output: out }));
  });
}

// Compile every project source with the host compiler, *without* IMGUI_STUDIO,
// to prove the code does not depend on the Studio runtime.
export async function nativeCheck(studio) {
  const projectDir = studio.projectDir;
  const cfg = loadProjectConfig(projectDir);
  const host = findHostCompiler();
  if (!host) return { ok: null, skipped: true, reason: 'No host C++ compiler found (tried $CXX, clang++, g++, c++)' };
  const imguiDir = imguiDirFor(projectDir, cfg);
  const sources = projectSources(projectDir, cfg);
  const flags = [`-std=${cfg.cxx_std}`, '-fsyntax-only', `-I${imguiDir}`, `-I${path.join(RUNTIME_DIR, 'include')}`];
  for (const inc of cfg.include_dirs) {
    const abs = path.resolve(projectDir, inc);
    if (fs.existsSync(abs)) flags.push(`-I${abs}`);
  }
  for (const d of cfg.defines) flags.push(`-D${d}`);
  if (/clang/.test(host.version)) flags.push('-fno-color-diagnostics');
  else flags.push('-fdiagnostics-color=never');
  const mapPath = makePathMapper({ projectDir, studioRoot: STUDIO_ROOT });
  const results = await mapLimit(sources, Math.max(1, os.cpus().length), async (rel) => {
    const r = await run(host.cxx, [...flags, path.join(projectDir, rel)], { cwd: projectDir });
    return { file: rel, ok: r.code === 0, output: r.output };
  });
  const diags = parseDiagnostics(results.map((r) => r.output).join('\n'), mapPath);
  return {
    ok: results.every((r) => r.ok),
    compiler: host.version,
    checked: sources,
    failed: results.filter((r) => !r.ok).map((r) => r.file),
    errors: diags.filter((d) => d.severity === 'error'),
    warnings: diags.filter((d) => d.severity === 'warning').slice(0, 20),
    note: 'Sources were compiled without IMGUI_STUDIO (studio.h macros disabled), as in a native application.',
  };
}
