// Project scaffolding: templates, bundled fonts, and the Claude Code "agent kit"
// (design skill + designer instructions + MCP config) that makes every Claude
// Code session in a project start with the premium design skill loaded.
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { STUDIO_ROOT, TEMPLATES_DIR } from './config.js';

export const SKILL_NAME = 'imgui-premium-menu-design';
export const SKILL_FILE = path.join(STUDIO_ROOT, '.claude', 'skills', SKILL_NAME, 'SKILL.md');
export const DESIGNER_FILE = path.join(STUDIO_ROOT, 'agent', 'designer.md');
export const AGENT_NAME = 'imgui-menu-designer';
export const SKILL_IMPORT = `@.claude/skills/${SKILL_NAME}/SKILL.md`;
const FONTS_DIR = path.join(TEMPLATES_DIR, 'showcase', 'assets', 'fonts');

export function listTemplates() {
  return fs.readdirSync(TEMPLATES_DIR).filter((d) => fs.existsSync(path.join(TEMPLATES_DIR, d, 'studio.json')));
}

export async function createProject(dest, { template = 'showcase', name = null, agentKit = true } = {}) {
  const src = path.join(TEMPLATES_DIR, template);
  if (!fs.existsSync(path.join(src, 'studio.json'))) throw new Error(`Unknown template "${template}" (available: ${listTemplates().join(', ')})`);
  if (fs.existsSync(dest) && fs.readdirSync(dest).length) throw new Error(`${dest} already exists and is not empty`);
  await fsp.cp(src, dest, { recursive: true, filter: (p) => !p.split(path.sep).includes('.studio') });
  // Every project gets Inter so agents never fall back to the bitmap default font.
  const fonts = path.join(dest, 'assets', 'fonts');
  if (!fs.existsSync(fonts) && fs.existsSync(FONTS_DIR)) await fsp.cp(FONTS_DIR, fonts, { recursive: true });
  if (name) {
    const f = path.join(dest, 'studio.json');
    const cfg = JSON.parse(await fsp.readFile(f, 'utf8'));
    cfg.name = name;
    await fsp.writeFile(f, `${JSON.stringify(cfg, null, 2)}\n`);
  }
  if (agentKit) await installAgentKit(dest);
  return dest;
}

// Subagent definition: the skill is preloaded through the `skills` frontmatter
// field, so it is in context from the subagent's first turn.
export function subagentDefinition() {
  const designer = fs.readFileSync(DESIGNER_FILE, 'utf8');
  return `---
name: ${AGENT_NAME}
description: Designs and implements bespoke, premium Dear ImGui menus in C++ with ImGui Studio (build, screenshot, inspect, interact, compare, export). Use for any request to create, redesign, polish or match a reference for an ImGui menu.
tools: Read, Edit, Write, Glob, Grep, mcp__imgui-studio__*
model: opus
skills:
  - ${SKILL_NAME}
---

<!-- Generated by \`imgui-studio agent-kit\` from agent/designer.md. Do not edit by hand. -->

${designer}`;
}

// Install the Claude Code integration into a project directory.
export async function installAgentKit(projectDir, { studioBin = path.join(STUDIO_ROOT, 'bin', 'imgui-studio.js') } = {}) {
  const dir = path.resolve(projectDir);
  const written = [];
  const write = async (rel, content) => {
    const abs = path.join(dir, rel);
    await fsp.mkdir(path.dirname(abs), { recursive: true });
    await fsp.writeFile(abs, content);
    written.push(rel);
  };
  await write(`.claude/skills/${SKILL_NAME}/SKILL.md`, await fsp.readFile(SKILL_FILE));
  await write(`.claude/agents/${AGENT_NAME}.md`, subagentDefinition());
  await write('.claude/imgui-studio/designer.md', await fsp.readFile(DESIGNER_FILE));

  const mcpFile = path.join(dir, '.mcp.json');
  let mcp = { mcpServers: {} };
  try {
    mcp = JSON.parse(await fsp.readFile(mcpFile, 'utf8'));
    mcp.mcpServers ||= {};
  } catch {
    // new file
  }
  mcp.mcpServers['imgui-studio'] = { command: process.execPath, args: [studioBin, 'mcp', '--project', dir] };
  await write('.mcp.json', `${JSON.stringify(mcp, null, 2)}\n`);

  const claudeMd = path.join(dir, 'CLAUDE.md');
  const existing = fs.existsSync(claudeMd) ? await fsp.readFile(claudeMd, 'utf8') : '';
  if (!existing.includes(SKILL_IMPORT)) {
    const block = `<!-- imgui-studio agent kit: the imports below load the designer instructions and the
     ${SKILL_NAME} skill in full at the start of every Claude Code session here. -->
@.claude/imgui-studio/designer.md
${SKILL_IMPORT}
`;
    const header = existing ? `${existing.trimEnd()}\n\n` : `# Dear ImGui project (ImGui Studio)\n\nThe \`imgui-studio\` MCP server (see .mcp.json) builds this project to WebAssembly and lets you\nscreenshot, inspect and drive the real Dear ImGui UI. Open the Studio at the URL it prints to watch.\n\n`;
    await write('CLAUDE.md', `${header}${block}`);
  }
  return { project: dir, written };
}

export function projectImportsSkill(projectDir) {
  try {
    return fs.readFileSync(path.join(projectDir, 'CLAUDE.md'), 'utf8').includes(SKILL_IMPORT);
  } catch {
    return false;
  }
}
